
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - fwx/shoulder_pan_joint
     - fwx/shoulder_lift_joint
     - fwx/elbow_joint
     - fwx/wrist_1_joint
     - fwx/wrist_2_joint
     - fwx/wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      fwx/shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      fwx/shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      fwx/elbow_joint: {trajectory: 0.1, goal: 0.1}
      fwx/wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      fwx/wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      fwx/wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gains:
  #   ur10shoulder_pan_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10shoulder_lift_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10elbow_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10wrist_1_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10wrist_2_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10wrist_3_joint:  {p: 10,  d: 1, i: 1, i_clamp: 1}
# gazebo_ros_control: 
#   pid_gains:
#     ur10shoulder_pan_joint: {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10shoulder_lift_joint: {p: 100, d: 0, i: 10.0, i_clamp: 50}
#     ur10elbow_joint:  {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10wrist_1_joint:  {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10wrist_2_joint:  {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10wrist_3_joint:   {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
